apiVersion: apps/v1
kind: Deployment
metadata:
  name: arclight-agency
  labels:
    app: arclight-agency

spec:
  replicas: 2

  selector:
    matchLabels:
      app: arclight-agency

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: arclight-agency

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      securityContext:
        fsGroup: 101

      containers:
        - name: arclight-agency
          image: ghcr.io/kgomotso1995/arclight_agency