apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloom-cafe
  labels:
    app: bloom-cafe

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bloom-cafe

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: bloom-cafe

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      securityContext:
        fsGroup: 101
      containers:
        - name: bloom-cafe
          image: ghcr.io/kgomotso1995/bloom-cafe:latest
          imagePullPolicy: Always