apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-tech
  labels:
    app: nova-tech

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nova-tech

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: nova-tech

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      securityContext:
        fsGroup: 101
      containers:
        - name: nova-tech
          image: ghcr.io/kgomotso1995/nova-tech:latest
          imagePullPolicy: Always