apiVersion: v1
kind: Service
metadata:
  name: nova-tech
  namespace: default
  labels:
    app: nova-tech
spec:
  selector:
    app: nova-tech
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP