apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: ghcr.io/kgomotso1995/arclight_agency
    newTag: staging

commonLabels:
  env: staging