apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bloom-cafe-staging
  namespace: argocd
  labels:
    env: staging
spec:
  project: default
  source:
    repoURL: https://github.com/Kgomotso1995/cicd-pipeline-using-github-actions-k8s-argocd
    targetRevision: staging
    path: apps/bloom-cafe/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true