apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova-tech-prod
  namespace: argocd
  labels:
    env: production
spec:
  project: default
  source:
    repoURL: https://github.com/Kgomotso1995/cicd-pipeline-using-github-actions-k8s-argocd
    targetRevision: main
    path: apps/nova-tech/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sites-prod
  syncPolicy:
    automated:
      prune: false  # Manual sync for production
      selfHeal: false