apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova-tech-dev
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/Kgomotso1995/cicd-pipeline-using-github-actions-k8s-argocd
    targetRevision: dev
    path: apps/nova-tech/k8s
    directory:
      include: deployment-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true