apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdant_homes-staging
  namespace: argocd
  labels:
    env: staging
spec:
  project: default
  source:
    repoURL: https://github.com/Kgomotso1995/cicd-pipeline-using-github-actions-k8s-argocd
    targetRevision: staging
    path: apps/verdant_homes/k8s
    directory:
      include: deployment-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
          prune: true
          selfHeal: true
    syncOptions:
      - CreateNamespace=true
