apiVersion: v1
kind: Service
metadata:
  name: zenfit-studio-service
  labels:
    app: zenfit-studio

spec:
  type: ClusterIP

  selector:
    app: zenfit-studio

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80